export const name = "João Sousa-Pinto, DPhil";
export const title = "Staff ML Engineer at Tesla";
export const summary = "I am an applied scientist with a background in computer science and mathematics. I have a track record of 12+ years of innovation in robotics, motion planning, optimization, control, machine learning, and CS theory.";

export const experience = [
  {
    company: "Tesla",
    role: "Staff Machine Learning Engineer",
    period: "2024 - Present",
    description: "Train end-to-end driving models for full self-driving (FSD)."
  },
  {
    company: "Apple",
    role: "Staff Machine Learning Engineer",
    period: "2019 - 2024",
    description: "Tech lead for trajectory optimization."
  },
  {
    company: "drive.ai",
    role: "Senior Software Engineer",
    period: "2017 - 2019",
    description: "Worked on motion planning for autonomous vehicles."
  }
];

export const publications = [
  {
    title: "Dual-Regularized Riccati Recursions for Interior-Point Optimal Control",
    venue: "arXiv preprint, 2025",
    arxiv: "https://arxiv.org/abs/2509.16370",
    description: "Closed-form extensions of Riccati recursions for solving dual-regularized LQR problems."
  },
  {
    title: "Primal-Dual iLQR for GPU-Accelerated Learning and Control in Legged Robots",
    venue: "RA-L, 2025 + ICRA, 2026",
    arxiv: "https://arxiv.org/abs/2506.07823",
    official: "https://ieeexplore.ieee.org/document/11248841",
    description: "GPU-parallelized Model-Predictive Control (MPC) of legged locomotion systems in logarithmic parallel time complexity."
  },
  {
    title: "An efficient algorithm for solving linear equality-constrained LQR problems",
    venue: "arXiv preprint, 2024",
    arxiv: "https://arxiv.org/abs/2407.05433",
    description: "Provides a mechanism for reducing equality-constrained LQR problems to unconstrained ones."
  },
  {
    title: "On the decidability of membership in matrix-exponential semigroups",
    venue: "JACM, 2019",
    arxiv: "",
    official: "https://dl.acm.org/doi/10.1145/3286487",
    description: "Investigates whether it is possible to algorithmically decide if a given matrix belongs to a semigroup generated by matrix exponentials."
  },
  {
    title: "On the decidability of reachability in linear time-invariant systems",
    venue: "HSCC, 2019",
    arxiv: "https://arxiv.org/abs/1802.06575",
    official: "https://dl.acm.org/doi/10.1145/3302504.3311796",
    description: "Characterizes the computational hardness of state-to-state reachability in linear time-invariant control systems."
  },
  {
    title: "On the polytope escape problem for continuous linear dynamical systems",
    venue: "HSCC, 2017",
    arxiv: "https://arxiv.org/abs/1507.03166",
    official: "https://dl.acm.org/doi/abs/10.1145/3049797.3049798",
    description: "Addresses the 'escape problem,' which asks whether a trajectory of a continuous linear system will ever exit a defined polyhedral region."
  },
  {
    title: "Solvability of matrix-exponential equations",
    venue: "LICS, 2016",
    arxiv: "https://arxiv.org/abs/1601.05002",
    official: "https://dl.acm.org/doi/abs/10.1145/2933575.2934538",
    description: "A theoretical study on the conditions and decidability of solving equations that involve matrix exponentials."
  },
  {
    title: "On termination of integer linear loops",
    venue: "SODA, 2015",
    arxiv: "https://arxiv.org/abs/1407.1891",
    official: "https://epubs.siam.org/doi/10.1137/1.9781611973730.65",
    description: "A fundamental study on the decidability and complexity of determining loop termination for integer linear transformations."
  }
];

export const projects = [
  {
    name: "SIP",
    url: "https://github.com/joaospinto/sip",
    description: "A high-performance C++ optimizer for general constrained nonconvex problems, allowing the user to provide custom routines for efficient problem-specific linear algebra operations."
  },
  {
    name: "SLACG",
    url: "https://github.com/joaospinto/slacg",
    description: "Generates C++ code for sparse linear algebra operations which avoids spending any runtime on index computations."
  },
  {
    name: "SIP Optimal Control",
    url: "https://github.com/joaospinto/sip_optimal_control",
    description: "Implements an optimal control-specific front-end for the SIP solver back-end."
  },
  {
    name: "Primal-Dual LIPA",
    url: "https://github.com/joaospinto/primal-dual-lipa",
    description: "Implements a GPU-accelerated interior point optimal control solver in JAX."
  },
  {
    name: "Binary NN for MNIST",
    url: "https://github.com/joaospinto/boolean-weight-mnist",
    description: "Trains a binary NN for MNIST, showcasing an interesting quantization strategy."
  }
];

export const education = [
  {
    institution: "University of Oxford",
    degree: "DPhil Computer Science",
    period: "2013 - 2017",
    details: "Decidability boundaries in linear dynamical systems.",
    thesis: "https://ora.ox.ac.uk/objects/uuid:9dde757f-6de1-47a6-a628-73f46e4bdf70"
  },
  {
    institution: "University of Oxford",
    degree: "MSc Computer Science",
    period: "2012 - 2013",
    details: "Graduated with distinction."
  },
  {
    institution: "University of Porto",
    degree: "BSc Mathematics",
    period: "2009 - 2012",
    details: "Valedictorian, 19/20 GPA."
  }
];
